Update Books.model.js
SST-OSS/ScalerKeep pull request #8
Opened 2023-10-27 15:45 UTC by narasimha-1511

Fixig Typo Errors..

2023-10-27 16:09 UTC, probablyArth requested changes

2023-10-27 16:09 UTC, probablyArth commented on server/models/Books.model.js
> +const BooksModel = model(USER_MODEL_NAME, BooksSchema);
should be `BOOKS_MODEL_NAME`

2023-10-27 16:22 UTC, narasimha-1511 commented on server/models/Books.model.js
> +const BooksModel = model(USER_MODEL_NAME, BooksSchema);
Resolved

2023-10-28 08:44 UTC, probablyArth approved these changes
LGTM!

2023-10-28 08:44 UTC, merged